### ISSUE TITLE
[ASKING] Will it work on ADSBx image?

### ISSUE THREAD

**Issue by Indr1d-C0ld** [shbisson/OverPutney#5]
Hello friend, sorry to bother you but I have to ask: I'm using ADSB Exchange SD image and configured it on my Raspberry Pi 3B+ with Buster Lite and no GUI. I'm already using tweepi to automatically post on Twitter, but in your opinion can I use your awesome scripts in this configuration?

**Comment by shbisson** [comment]
If you’re using the latest ADSBE image with tar1090 it should work; as it’s just using the tar1090 map and the aircraft data JSON file. You’ll find the values uses in the config file which you should edit for your Twitter API keys and location and any tweaks you want to make to the tweet templates.

Cheers!

S.
--
Simon Bisson
Freelance Technology Writer
mail: simon@sandm.co.uk<mailto:simon@sandm.co.uk> | web: www.sandm.co.uk<http://www.sandm.co.uk/> |blog: www.simonbisson.co.uk<http://www.simonbisson.co.uk/>
phone: +44 7970 787068 / +44 7307 416574 | skype: sbisson | twitter: @sbisson

**Comment by shbisson** [comment]
The only packages I believe need to be installed are chromium-chromedriver, python3, and python3-pip (as the python3 build does not include the pip package installer).

You can then use pip to install the pillow, requests, twitter and selenium modules.

**Comment by shbisson** [comment]
The only packages I believe need to be installed are chromium-chromedriver, python 3, and python3-pip (as the python3 build does not include the pip package installer).

You can then use pip to install the pillow, requests, twitter and selenium modules.

I will be writing installation documentation shortly.

**Comment by Indr1d-C0ld** [comment]
Here's the steps I've done in my system, pre-existent ADSBx ADS-B Exchange image with additional software and configurations, in RPi3b+:

python3 -m pip install --upgrade pip

python3 -m pip install --upgrade twitter

Add to .bashrc:
---------------------------------------
# Directory to PATH
export PATH="/home/pi/.local/bin:$PATH"
---------------------------------------

python3 -m pip install --upgrade selenium

python3 -m pip install --upgrade Pillow

python3 -m pip install --upgrade requests

sudo apt-get install chromium-driver -y

configure 'config' and then rename it 'config.ini'

exec runbot.sh (tail -f nohup.out to monitor output)

**Comment by shbisson** [comment]
That is what I did; not sure why this is not working for you. It might be worth checking that the screenshot file tweet.png is saved in the bot directory?

**Comment by Indr1d-C0ld** [comment]
I'll take a look to that file friend, maybe a permission issue or something like that?
