### ISSUE TITLE
Error with run_tracker.sh

### ISSUE THREAD

**Issue by Indr1d-C0ld** [shbisson/OverPutney#6]
./run_tracker.sh: riga 8: py3/bin/activate: File o directory non esistente

(file or directory not existent)

Can you help me solve this issue? Script goes ahead but I always find this error in the beginning. I'm using Raspbian Buster on Raspberry 3B+, thanks a lot.

**Comment by Indr1d-C0ld** [comment]
Also, every flight detail will be posted but... no picture of the same, here's the log (maybe the fault is of the error in the 1st post?):
-----------------------------------------------------------------------------------------
***** Restarting OverPutney  2020-10-13 21:27:40.055120086+00:00

will crop
getting web page http://localhost/tar1090/
waiting for page to load...
reset map:
zoom in 3 times:
<selenium.webdriver.remote.webelement.WebElement (session="eb6a3e1e732f1f7a814db42578fa04d1", element="934e6aae-9dc6-4308-947c-3aa315534e04")>
time to create screenshot of <AirCraftData 471F8E/WZZ4KB   dist=130.17767250920545 el=3.162340861971428>:
number of elements found: 1
clicking on 471F8E!
time to tweet!!!!!
#WZZ4KB n/a n/a n/a, squawk 1000: 209.5 km away @ 11574.8 m and 3.2° from horizon, heading NE @ 938.4km/h 23:28:14. #AfterHours #WayTheHeckUpThere #FlyingFast #ADSB #dump1090 #flight #planespotting #radar #sdr #grosseto #lirs #adsbexchange

And... no image posted. Thanks!

**Comment by shbisson** [comment]
Check that you have pillow correctly installed for screenshots to work.

https://pillow.readthedocs.io/en/stable/installation.html

**Comment by Indr1d-C0ld** [comment]
But I've already installed Pillow, I don't see errors on screen, the crop of the image is enabled too...

**Comment by shbisson** [comment]
Hmm. I notice from your log that you don't seem to be cropping and saving the screenshot. This is what I get, I see the same clicking on entry, but then the next two lines don't seem to be printed to the log file; so there's something odd happening in screenshot.py.

clicking on 06A2DF!
cropping screenshot
success saving screenshot: tweet.png
time to tweet!!!!!

**Comment by Indr1d-C0ld** [comment]
Mmmh... maybe for PNG file exists a prerequisite lib for Pillow?

**Comment by kwbisch** [comment]
Has anyone ever figured this out?  I'm having the same trouble.  Pillow appears to be installed....

**Comment by chilledgecko** [comment]
I have the same issue, it's not something I've had the time to look at yet. - It's on the list...
I detect and tweet the plane but there is no associated image.

**Comment by kwbisch** [comment]
> I have the same issue, it's not something I've had the time to look at yet. - It's on the list...
> I detect and tweet the plane but there is no associated image.
> 
> Just checked Pillow 8.0.1 is installed and PIL is not found.
> Running on Pi4 with Buster

Everything the same here, except it's a RasPi 3 B+ running the PiAware image.

**Comment by hprlange** [comment]
Same probleme here.

**Comment by chilledgecko** [comment]
The solution is explained in issue #7.
It's a tar1090 config issue.

Worked for me 👍
