### ISSUE TITLE
No screenshots taken - Element not interactable

### ISSUE THREAD

**Issue by biohead** [shbisson/OverPutney#7]
After having a similar issue (no screenshot but different error message) on a FA image, I've attempted using a completely fresh image of ADSBx Buster (1.0.6) on Pi 4B.

Bot is unable to take a screenshot - but successfully posts the text tweet to twitter.

python3 -m install --upgrade twitter
add 'export PATH="/home/pi/.local/bin:$PATH"' to the bottom of .bashrc
python3 -m install --upgrade Pillow 
python3 -m install --upgrade selenium
python3 -m install --upgrade requests
sudo apt-get install chromium-chromedriver

chromium/stable 83.0.4103.116-1~deb10u2 armhf
chromium-chromedriver/testing,now 84.0.4147.105-rpt3 armhf 

Example error message given (using ADSBx image):

```
time to create screenshot of <AirCraftData C023C7/ACA7157  dist=3.5696016885006387 el=63.61919729087339>:
number of elements found: 1
clicking on C023C7!
Could not click on airplane: Message: element not interactable
  (Session info: headless chrome=84.0.4147.141)
time to tweet!!!!!
#ACA7157 n/a n/a n/a: 3.6 mi away @ 38000 ft and 63.6° frm hrzn, heading NW @ 647.6mi/h 13:20:47. #WayTheHeckUpThere #FlyingFast #OverBracknell #Testing #Bracknell #RG12 #RG42 #ADSB #dump1090
```

On the FA image, the error is slightly different:

```
time to create screenshot of <AirCraftData 43C5E1/RRR4672  dist=1.6984907925654387 el=69.49130710853093>:
number of elements found: 0
couldn't find the object
time to tweet!!!!!
#RRR4672 0 0 0: 1.7 mi away @ 23975 ft and 69.5° frm hrzn, heading E @ 426.6mi/h 13:49:49. #UpInTheClouds #MovingQuickly #AboveBracknell #Bracknell #RG12 #RG42 #ADSB #dump1090
```

**Comment by biohead** [comment]
Reverting back to commit 396ca2c on the same hardware gives working screenshots, albeit using dump1090-fa.

**Comment by biohead** [comment]
Tar1090 needs a change in config.js to make sure the ICAO Hex code is listed in the default layout of the table.

I'm not sure if there's been a change to Tar1090, or if this instruction needs to be added to the Readme.

**Comment by hprlange** [comment]
Not sure what kind of change is mentioned. Can you describe it in more detail?

**Comment by chilledgecko** [comment]
As mentioned by biohead, the config.is file needs modification.

Try the following;

To enable Tar1090 web screenshots the tar1090 config.js needs to be edited. 
[ sudo nano /usr/local/share/tar1090/html/config.js ] and remark out (//) the ICAO line in the HideCols section.

**Comment by hprlange** [comment]
Incredible, but it works!

**Comment by louwng** [comment]
My tar1090 installation runs in a docker container where will I find the config.js to update?

**Comment by louwng** [comment]
> After having a similar issue (no screenshot but different error message) on a FA image, I've attempted using a completely fresh image of ADSBx Buster (1.0.6) on Pi 4B.
> 
> Bot is unable to take a screenshot - but successfully posts the text tweet to twitter.
> 
> python3 -m install --upgrade twitter add 'export PATH="/home/pi/.local/bin:$PATH"' to the bottom of .bashrc python3 -m install --upgrade Pillow python3 -m install --upgrade selenium python3 -m install --upgrade requests sudo apt-get install chromium-chromedriver
> 
> chromium/stable 83.0.4103.116-1~deb10u2 armhf chromium-chromedriver/testing,now 84.0.4147.105-rpt3 armhf
> 
> Example error message given (using ADSBx image):
> 
> ```
> time to create screenshot of <AirCraftData C023C7/ACA7157  dist=3.5696016885006387 el=63.61919729087339>:
> number of elements found: 1
> clicking on C023C7!
> Could not click on airplane: Message: element not interactable
>   (Session info: headless chrome=84.0.4147.141)
> time to tweet!!!!!
> #ACA7157 n/a n/a n/a: 3.6 mi away @ 38000 ft and 63.6° frm hrzn, heading NW @ 647.6mi/h 13:20:47. #WayTheHeckUpThere #FlyingFast #OverBracknell #Testing #Bracknell #RG12 #RG42 #ADSB #dump1090
> ```
> 
> On the FA image, the error is slightly different:
> 
> ```
> time to create screenshot of <AirCraftData 43C5E1/RRR4672  dist=1.6984907925654387 el=69.49130710853093>:
> number of elements found: 0
> couldn't find the object
> time to tweet!!!!!
> #RRR4672 0 0 0: 1.7 mi away @ 23975 ft and 69.5° frm hrzn, heading E @ 426.6mi/h 13:49:49. #UpInTheClouds #MovingQuickly #AboveBracknell #Bracknell #RG12 #RG42 #ADSB #dump1090
> ```

I am getting the same error where it complains about :

"number of elements found: 0"
"couldn't find the object"
"time to tweet !!!!!!"
#00C455 00C455 ZS-ZWE Boeing 737NG 8LD/W Kulula.com: 30.9 km away @ 2750 ft and 1.6° frm hrzn, heading N @ 0.0km/h 15:33:27. #OverStrand #Strand #ADSB #tar1090

I have tracked it down to screenshot.py but cannot figure out what is wrong, please help !!!

regards
Nico
